apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: example
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: workers
    replicas: 2 # set to number of node pools
    template:
      spec:
        parallelism: 3
        completions: 3
        backoffLimit: 10
        template:
          spec:
            containers:
            - name: sleep
              image: busybox
              command: 
                - sleep
              args:
                - 1000s