apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: nicks-two-slice
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
  labels:
    some-custom-jobset-label-key: "some-custom-jobset-label-value"
spec:
  failurePolicy:
    maxRestarts: 0
  replicatedJobs:
    - name: slice
      replicas: 2
      template:
        spec:
          parallelism: 1
          completions: 1
          backoffLimit: 0
          template:
            spec:
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v5p-slice
                cloud.google.com/gke-tpu-topology: 2x2x1
                cloud.google.com/gke-spot: "true"
              tolerations:
              - key: cloud.google.com/gke-spot
                operator: Equal
                value: "true"
                effect: NoSchedule
              containers:
              - name: jax-tpu
                image: python:3.8
                ports:
                - containerPort: 8471
                - containerPort: 8080
                command:
                - bash
                - -c
                - |
                  pip install "jax[tpu]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
                  python -c 'import jax; print("Global device count:", jax.device_count())'
                  sleep 60
                resources:
                  limits:
                    google.com/tpu: 4
