apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kube-state-metrics-custom
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics
  endpoints:
  - port: 8080
    interval: 30s